apiVersion: v1
kind: Service
metadata:
  name: kwetter-search-db
  namespace: kwetter
  labels:
    app: kwetter-search-db
    service: kwetter-search-db
spec:
  selector:
    app: kwetter-search-db-pod
  ports:
    - protocol: TCP
      name: tcp-psql
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetter-search-db
  namespace: kwetter
spec:
  selector:
    matchLabels:
      app: kwetter-search-db-pod
      version: latest
  template:
    metadata:
      labels:
        app: kwetter-search-db-pod
        version: latest
    spec:
      containers:
        - name: kwetter-search-db-container
          image: postgres:13.3
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 200Mi
              cpu: 300m
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: kwetter-search-db-secret
            - configMapRef:
                name: kwetter-search-db-config
          volumeMounts:
            - name: kwetter-search-db-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: kwetter-search-db-volume
          persistentVolumeClaim:
            claimName: kwetter-search-db-volume-claim