apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kwetter-search-db-volume-claim
  namespace: kwetter
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-premium
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: kwetter-search-db-volume
#  namespace: kwetter
#  labels:
#    type: local
#spec:
#  capacity:
#    storage: 4Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: managed-premium
#  local:
#    path: /mnt/data/kwetter-search-db/
#  claimRef:
#    apiVersion: v1
#    kind: PersistentVolumeClaim
#    name: kwetter-search-db-volume-claim
#    namespace: kwetter
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - minikube