apiVersion: v1
kind: Secret
metadata:
  name: profile-service-secret
type: Opaque
stringData:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionString: "Host=kwetter-profile-db;Database=user;Username=postgres;Password=mysecretpassword"