apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: kwetter
  labels:
    app: profile-service
spec:
  selector:
    app: profile-service-pod
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  type: ClusterIP