name: CodeQuality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - src/Services/**

defaults:
  run:
    working-directory: src
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration "Services Build"
      
  codequality:
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Test dotnet
        run: dotnet test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          fetch-depth: 0
          args: >
            -Dsonar.organization=rvalkenburg
            -Dsonar.projectKey=rvalkenburg_kwetter-backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
