name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: src    

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  build-docker:
    needs: [ build ]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build the docker ProfileService image
        run: docker build . --file  services/ProfileService/Rest/ProfileService.Dockerfile --tag my-image-name:$(date +%s)
      - name: Build the docker KweetService image
        run: docker build . --file services/KweetService/Rest/KweetService.Dockerfile --tag my-image-name:$(date +%s)

